#!/bin/bash -i

hl() {
    echo "$1" | highlight -S bash -O xterm256
}

hl_wait() {
    echo -n $(hl "$1")
    read </dev/tty
}

hl_cmd() {
    local PS1='\033[01;34m\w\033[00m$ '
    echo -n "${PS1@P}"
    local cmd=$(echo "$1" | cut -d';' -f2)
    hl_wait "$(echo $cmd)"
}

echo -e "\n========== Press [Enter] to continue ==========\n" | egrep '.*'

"$@" 2>&1 |\
while IFS='^$&' read line; do
    case $line in
        [#][#]*)    hl_wait "$line" ;;
        [:]*\;*)    hl_cmd "$line"  ;;
        [:]*|[#]*)  hl "$line"      ;;
        *)          echo "$line"    ;;
    esac
done

echo -e "\n========== PLAY: $@ : DONE ==========\n" | egrep '.*'
