#!/bin/bash -i
#
# Usage: [DELAY=<secs>] play <bash-script>
#
# Run the script and stop on comments that start with '##*' and on
# commands that start with ':*;*'. Highlight these commands and
# comments, as well as comments that start with '#*' or ':*'.
#
# The given <bash-script> has to set 'set -o verbose' on top of it.
#
# If it called with a delay, like this:
#     DELAY=0.7 play bash-script.sh
# Then it will stop that amount of time, instead of waiting for
# [Enter] to continue.

hl() {
    echo "$1" | highlight -S bash -O xterm256
}

hl_wait() {
    echo -n $(hl "$1")
    [[ -z $DELAY ]] && read </dev/tty || { sleep $DELAY; echo; }
}

hl_cmd() {
    local PS1='\033[01;34m\w\033[00m$ '
    echo -n "${PS1@P}"
    local cmd=$(echo "$1" | cut -d';' -f2)
    hl_wait "$(echo $cmd)"
}

[[ -z $DELAY ]] && echo -e "\n========== Press [Enter] to continue ==========\n" | egrep '.*'

"$@" 2>&1 |\
while IFS='^$&' read line; do
    case $line in
        [#][#]*)    hl_wait "$line" ;;
        [:]*\;*)    hl_cmd "$line"  ;;
        [:]*|[#]*)  hl "$line"      ;;
        *)          echo "$line"    ;;
    esac
done

[[ -z $DELAY ]] && echo -e "\n========== PLAY: $@ : DONE ==========\n" | egrep '.*'
